## LEARNING NUMPY

# Importing Numpy

In [1]:
# Importing Numpy:
import numpy as np

### Creating Array From List

In [2]:
arr_1d = np.array([1,2,3])
print('1D Array:', arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print('2D Array:\n', arr_2d)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


### Python List VS NumPy Array

In [3]:
py_list = [1,2,3]
print("Python List Multiplication: ", py_list * 2)

np_array = np.array([4,5,6]) # Element Wise Multiplication
print("Python Array [NumPy] Multiplication: ", np_array * 2)

Python List Multiplication:  [1, 2, 3, 1, 2, 3]
Python Array [NumPy] Multiplication:  [ 8 10 12]


In [4]:
# Working With Time And Numpy:
import time
# Python List
start = time.time()
py_list1 = [x * 2 for x in range(1000000)]
print("\n List Operation Time:", time.time() - start)

# NumPy Or Python Array
start = time.time()
np_array1 = np.arange(1000000) * 2
print("\n NumPy Operation Time:", time.time() - start)


 List Operation Time: 0.13056182861328125

 NumPy Operation Time: 0.006451845169067383


### Creating Array From Scratch

In [5]:
# Creating Array Of Zeros:
zeros = np.zeros((3, 4))
print("Zero Array: \n", zeros)

# Creating Array For Ones:
ones = np.ones((3, 4))
print("One Array: \n", ones)

# Creating Constant Array:
full = np.full((3, 4), 7)
print("Full Array: \n", full)

# Creating Random Array:
random = np.random.random((3, 4))
print("Random Array: \n", random)

# Creation Sequence Of Array Using ARRAnge:
seq = np.arange(0, 10, 2)    # (start, stop, step)
print("Sequence Array: \n", seq)

Zero Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Array: 
 [[0.57406801 0.67947533 0.88467586 0.5598652 ]
 [0.24942035 0.71674484 0.73290399 0.0633072 ]
 [0.99078735 0.92115341 0.58658364 0.57878825]]
Sequence Array: 
 [0 2 4 6 8]


### Vector, Matrix And Tensor

In [6]:
# Crearing Vector: (1 X N) - 1D
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

# Creating Matrix: (2 X N) - 2D
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Matrix: \n", matrix)

# Creating Tensor (N X N) - ND
tensor = np.array([[[1, 2], [3, 4],
                    [5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Array Properties

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print('Shape: ', arr.shape)
print('Size: ', arr.size)
print('Dimension: ', arr.ndim)
print('DType: ', arr.dtype)

Shape:  (2, 3)
Size:  6
Dimension:  2
DType:  int64


### Reshaping Array:

In [8]:
arr1 = np.arange(12)
print("Original Array:", arr1)

# Reshaping Our Original Array:
reshaped = arr1.reshape((3, 4))
print("Reshaped Array: \n", reshaped)

# Flatten Our Reshaped Array:
flattened = reshaped.flatten()
print("Flatten Array:", flattened)

# Raveled Our Reshaped Array:
# RAVEL [Return View, Instead Of Copy]
ravaled = reshaped.ravel()
print("Ravaled Array:", ravaled)

# Transposed Array:
transposed = reshaped.T
print("Transposed Array: \n", transposed)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravaled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
