## NumPy Array Opeartions:

In [1]:
import numpy as np

### Slicing & Indexing In NumPy:

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:7])
print("Slicing With Step:", arr[1:8:2])
print("Negative Indexing:", arr[-3])

Basic Slicing: [3 4 5 6 7]
Slicing With Step: [2 4 6 8]
Negative Indexing: 8


### Slicing And Indexing In 2D Array:

In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Accessing Particular Element In 2D Array:
print("One Particular Element (Of 2nd Row 3rd Col.):", arr_2d[1, 2])

# Accessing One  Entire Particular Row:
print("Entire 2nd Row:", arr_2d[1])

# Accessing Entire Column Of Our 2D Array:
print("One Entire Column Of Given Array (2nd Col):", arr_2d[:, 1])

One Particular Element (Of 2nd Row 3rd Col.): 6
Entire 2nd Row: [4 5 6]
One Entire Column Of Given Array (2nd Col): [2 5 8]


### Sorting In NumPy:

In [4]:
unsorted = np.array([6, 2, 4, 1, 5, 3])
# Sorting Our Array:
print("Sorted Array:", np.sort(unsorted))

Sorted Array: [1 2 3 4 5 6]


In [5]:
# Sorting 2D Array:
unsorted_2d_arr = np.array([[3, 8, 5],
                            [2, 7, 4],
                            [6, 1, 9]])
# Sorting Our 2D Array:
print("Sorted 2D Array By Row:\n", np.sort(unsorted_2d_arr, axis = 0))
print("Sorted 2D Array By Column:\n", np.sort(unsorted_2d_arr, axis = 1))

Sorted 2D Array By Row:
 [[2 1 4]
 [3 7 5]
 [6 8 9]]
Sorted 2D Array By Column:
 [[3 5 8]
 [2 4 7]
 [1 6 9]]


### Filtering In NumPy

In [8]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Filtering Even Number From Num Array:
even_num = num[num % 2 == 0]
print("Even Number:",even_num)

Even Number: [ 2  4  6  8 10]


### Filtering With Mask

In [9]:
mask = num > 5

# Printing Number Greater Than 5 Using Mask:
print("Number Greater Than 5:", num[mask])

Number Greater Than 5: [ 6  7  8  9 10]


### Fancy Indexing VS NP.WHERE()

In [13]:
indices = [0, 2, 4]

# Printing Value Of NUM Array Using Indicies:
print("Value At 1st, 3rd And 5th Position Of num Array:", num[indices])

# Creating Mask Using Where:
where_result = np.where(num > 5)
print("NP WHERE:", num[where_result])

Value At 1st, 3rd And 5th Position Of num Array: [1 3 5]
NP WHERE: [ 6  7  8  9 10]


In [16]:
# Using Where In Conditional:
condition_arr = np.where(num > 5, num * 5, num)
print(condition_arr)

# Understanding Above Code:
con_arr = np.where(num > 5, 'True', 'False')  # Its Like Using IF_ELSE Statement In Shorter Version
print("Printing True If Conditon Match Else False:",con_arr)

[ 1  2  3  4  5 30 35 40 45 50]
Printing True If Conditon Match Else False: ['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


### Adding And Removing Data:

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Merging Both Array:

# WARNING WE DON'T MERGE ARRAY LIKE THIS WE ADD LIKE THIS:
merg_arr = arr1 + arr2
print("Not Merged But Added Array:",merg_arr)

# For Merging Two Array We Use:
combined = np.concatenate((arr1, arr2))
print("Merged Array:", combined)

Not Merged But Added Array: [5 7 9]
Merged Array: [1 2 3 4 5 6]


### Array Compatibility:

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Checking Compatibilty;
print("Compatibility Shape:", a.shape == b.shape)

Compatibility Shape: True


### Add New Row And Column:

In [ ]:
# Adding New Row In Our Existing Array:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

# Adding New Row Using VSTACK:
with_new_row = np.vstack((original, new_row))
print("Original Array: \n", original)
print("Array With New Row: \n", with_new_row)

# Adding New Column Using HSTACK:
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("Array With New Column: \n", with_new_col)

Original Array: 
 [[1 2]
 [3 4]]
Array With New Row: 
 [[1 2]
 [3 4]
 [5 6]]
Array With New Column: 
 [[1 2 7]
 [3 4 8]]


### Deleting Data From Array:

In [29]:
arr = np.array([1, 2, 3, 4, 5])

# Deleting Data From 1D-Array Using Index:
deleted = np.delete(arr, 2)   # --> (From Which Array To Delete, Index -- Which Index Value To Delete)
print("Deleted 3rd Value Of Array:",deleted)

Deleted 3rd Value Of Array: [1 2 4 5]
